/*
 * Created on 2022-07-19 ( 21:02:45 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package backend.backend.persitence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Addrress"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "Addrress", schema = "dbo", catalog = "shop")
public class Addrress implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id", nullable = false)
    private Integer id;

    // --- ENTITY DATA FIELDS
    @Column(name = "province_id", nullable = false)
    private Integer provinceId;

    @Column(name = "district_id", nullable = false)
    private Integer districtId;

    @Column(name = "ward_code", nullable = false)
    private Integer wardCode;

    @Column(name = "sub_locate", nullable = false, length = 50)
    private String subLocate;

    // --- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "addrress")
    private List<Customer> listOfCustomer;

    @ManyToOne
    @JoinColumn(name = "province_id", referencedColumnName = "id", insertable = false, updatable = false)
    private AddrressCell addrressCell3;

    @ManyToOne
    @JoinColumn(name = "district_id", referencedColumnName = "id", insertable = false, updatable = false)
    private AddrressCell addrressCell2;

    @ManyToOne
    @JoinColumn(name = "ward_Code", referencedColumnName = "id", insertable = false, updatable = false)
    private AddrressCell addrressCell;

    @OneToMany(mappedBy = "addrress")
    private List<Shop> listOfShop;

    /**
     * Constructor
     */
    public Addrress() {
        super();
    }

    // --- GETTERS & SETTERS FOR FIELDS
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return this.id;
    }

    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    public Integer getProvinceId() {
        return this.provinceId;
    }

    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    public Integer getDistrictId() {
        return this.districtId;
    }

    public void setWardcode(Integer wardCode) {
        this.wardCode = wardCode;
    }

    public Integer getWardcode() {
        return this.wardCode;
    }

    public void setSubLocate(String subLocate) {
        this.subLocate = subLocate;
    }

    public String getSubLocate() {
        return this.subLocate;
    }

    // --- GETTERS FOR LINKS
    public List<Customer> getListOfCustomer() {
        return this.listOfCustomer;
    }

    public AddrressCell getAddrressCell3() {
        return this.addrressCell3;
    }

    public AddrressCell getAddrressCell2() {
        return this.addrressCell2;
    }

    public AddrressCell getAddrressCell() {
        return this.addrressCell;
    }

    public List<Shop> getListOfShop() {
        return this.listOfShop;
    }

    // --- toString specific method
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(id);
        sb.append("|");
        sb.append(provinceId);
        sb.append("|");
        sb.append(districtId);
        sb.append("|");
        sb.append(wardCode);
        sb.append("|");
        sb.append(subLocate);
        return sb.toString();
    }

}
