/*
 * Created on 2022-05-06 ( 17:51:46 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package backend.backend.persitence.entities;

import java.io.Serializable;


/**
 * Composite primary key for entity "CartItem" ( stored in table "Cart_Item" )
 *
 * @author Telosys
 *
 */
public class CartItemId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private Integer    idCustomer ;
    
    private Integer    idProduct ;
    
    /**
     * Constructor
     */
    public CartItemId() {
        super();
    }

    /**
     * Constructor with values
     * @param idCustomer 
     * @param idProduct 
     */
    public CartItemId( Integer idCustomer, Integer idProduct ) {
        super();
        this.idCustomer = idCustomer ;
        this.idProduct = idProduct ;
    }
    
    //--- GETTERS & SETTERS FOR KEY FIELDS
    public void setIdCustomer( Integer value ) {
        this.idCustomer = value;
    }
    public Integer getIdCustomer() {
        return this.idCustomer;
    }

    public void setIdProduct( Integer value ) {
        this.idProduct = value;
    }
    public Integer getIdProduct() {
        return this.idProduct;
    }


    //--- equals METHOD
	@Override
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		CartItemId other = (CartItemId) obj; 
		//--- Attribute idCustomer
		if ( idCustomer == null ) { 
			if ( other.idCustomer != null ) 
				return false ; 
		} else if ( ! idCustomer.equals(other.idCustomer) ) 
			return false ; 
		//--- Attribute idProduct
		if ( idProduct == null ) { 
			if ( other.idProduct != null ) 
				return false ; 
		} else if ( ! idProduct.equals(other.idProduct) ) 
			return false ; 
		return true; 
	} 

    //--- hashCode METHOD
	@Override
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute idCustomer
		result = prime * result + ((idCustomer == null) ? 0 : idCustomer.hashCode() ) ; 
		//--- Attribute idProduct
		result = prime * result + ((idProduct == null) ? 0 : idProduct.hashCode() ) ; 
		
		return result; 
	} 

    //--- toString METHOD
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idCustomer);
        sb.append("|");
        sb.append(idProduct);
        return sb.toString(); 
    } 

}
