/*
 * Created on 2022-05-06 ( 17:51:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package backend.backend.persitence.entities;

import java.io.Serializable;

/**
 * Composite primary key for entity "Chat" ( stored in table "Chat" )
 *
 * @author Telosys
 *
 */
public class ChatId implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY KEY ATTRIBUTES
    private Integer idAccount;

    private Integer idAccountReply;

    /**
     * Constructor
     */
    public ChatId() {
        super();
    }

    /**
     * Constructor with values
     * 
     * @param idAccount
     * @param idAccountReply
     */
    public ChatId(Integer idAccount, Integer idAccountReply) {
        super();
        this.idAccount = idAccount;
        this.idAccountReply = idAccountReply;
    }

    // --- GETTERS & SETTERS FOR KEY FIELDS
    public void setIdAccount(Integer value) {
        this.idAccount = value;
    }

    public Integer getIdAccount() {
        return this.idAccount;
    }

    public void setIdAccountReply(Integer value) {
        this.idAccountReply = value;
    }

    public Integer getIdAccountReply() {
        return this.idAccountReply;
    }

    // --- equals METHOD
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (this.getClass() != obj.getClass())
            return false;
        ChatId other = (ChatId) obj;
        // --- Attribute idAccount
        if (idAccount == null) {
            if (other.idAccount != null)
                return false;
        } else if (!idAccount.equals(other.idAccount))
            return false;
        // --- Attribute idAccountReply
        if (idAccountReply == null) {
            if (other.idAccountReply != null)
                return false;
        } else if (!idAccountReply.equals(other.idAccountReply))
            return false;
        return true;
    }

    // --- hashCode METHOD
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        // --- Attribute idAccount
        result = prime * result + ((idAccount == null) ? 0 : idAccount.hashCode());
        // --- Attribute idAccountReply
        result = prime * result + ((idAccountReply == null) ? 0 : idAccountReply.hashCode());

        return result;
    }

    // --- toString METHOD
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(idAccount);
        sb.append("|");
        sb.append(idAccountReply);
        return sb.toString();
    }

}
