/*
 * Created on 2022-05-06 ( 17:51:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package backend.backend.persitence.entities;


import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Chat"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Chat", schema="dbo", catalog="shop" )
@IdClass(ChatId.class)
public class Chat implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="id_account", nullable=false)
    private Integer    idAccount ;

    @Id
    @Column(name="id_account_reply", nullable=false)
    private Integer    idAccountReply ;

    //--- ENTITY DATA FIELDS 
    @Column(name="is_account_shop")
    private Boolean    isAccountShop ;

    @Column(name="is_account_reply_shop")
    private Boolean    isAccountReplyShop ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy="chat")
    private List<ChatLine> listOfChatLine ; 

    @ManyToOne
    @JoinColumn(name="id_account_reply", referencedColumnName="ID_ACCOUNT", insertable=false, updatable=false)
    private Account    account2 ; 

    @ManyToOne
    @JoinColumn(name="id_account", referencedColumnName="ID_ACCOUNT", insertable=false, updatable=false)
    private Account    account ; 


    /**
     * Constructor
     */
    public Chat() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdAccount( Integer idAccount ) {
        this.idAccount = idAccount ;
    }
    public Integer getIdAccount() {
        return this.idAccount;
    }

    public void setIdAccountReply( Integer idAccountReply ) {
        this.idAccountReply = idAccountReply ;
    }
    public Integer getIdAccountReply() {
        return this.idAccountReply;
    }

    public void setIsAccountShop( Boolean isAccountShop ) {
        this.isAccountShop = isAccountShop ;
    }
    public Boolean getIsAccountShop() {
        return this.isAccountShop;
    }

    public void setIsAccountReplyShop( Boolean isAccountReplyShop ) {
        this.isAccountReplyShop = isAccountReplyShop ;
    }
    public Boolean getIsAccountReplyShop() {
        return this.isAccountReplyShop;
    }

    //--- GETTERS FOR LINKS
    public List<ChatLine> getListOfChatLine() {
        return this.listOfChatLine;
    } 

    public Account getAccount2() {
        return this.account2;
    } 

    public Account getAccount() {
        return this.account;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idAccount);
        sb.append("|");
        sb.append(idAccountReply);
        sb.append("|");
        sb.append(isAccountShop);
        sb.append("|");
        sb.append(isAccountReplyShop);
        return sb.toString(); 
    } 

}
