/*
 * Created on 2022-05-06 ( 17:51:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package backend.backend.persitence.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "Customer"
 *
 * @author Telosys
 */
@Entity
@Table(name = "Customer", schema = "dbo", catalog = "shop")
public class Customer implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @Column(name = "id_customer", nullable = false)
    private Integer idCustomer;

    // --- ENTITY DATA FIELDS
    @Column(name = "name", length = 2147483647)
    private String name;

    @Column(name = "phone_number", length = 15)
    private String phoneNumber;

    @Column(name = "gender", length = 1)
    private String gender;

    @Temporal(TemporalType.DATE)
    @Column(name = "birthday")
    private Date birthday;

    @Column(name = "img_url", length = 2147483647)
    private String imgUrl;

    @Column(name = "pubkey", length = 2147483647)
    private String pubkey;

    @Column(name = "address_id", nullable = false)
    private String addressId;

    // --- ENTITY LINKS ( RELATIONSHIP )
    @OneToMany(mappedBy = "customer")
    private List<Evaluate> listOfEvaluate;

    @OneToOne
    @JoinColumn(name = "id_customer", referencedColumnName = "ID_ACCOUNT", insertable = false, updatable = false)
    @MapsId
    private Account account;

    @OneToMany(mappedBy = "customer")
    private List<OrderItem> listOfOrderItem;

    @OneToOne(mappedBy = "customer")
    private WalletCustomer walletCustomer;

    @OneToMany(mappedBy = "customer")
    private List<CartItem> listOfCartItem;

    @OneToOne
    @JoinColumn(name = "address_id", referencedColumnName = "id", insertable = false, updatable = false)
    private Addrress addrress;

    /**
     * Constructor
     */
    public Customer() {
        super();
    }

    // --- GETTERS & SETTERS FOR FIELDS
    public void setIdCustomer(Integer idCustomer) {
        this.idCustomer = idCustomer;
    }

    public Integer getIdCustomer() {
        return this.idCustomer;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getGender() {
        return this.gender;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getImgUrl() {
        return this.imgUrl;
    }

    public void setPubkey(String pubkey) {
        this.pubkey = pubkey;
    }

    public String getPubkey() {
        return this.pubkey;
    }

    // --- GETTERS FOR LINKS
    public List<Evaluate> getListOfEvaluate() {
        return this.listOfEvaluate;
    }

    public Account getAccount() {
        return this.account;
    }

    public List<OrderItem> getListOfOrderItem() {
        return this.listOfOrderItem;
    }

    public WalletCustomer getWalletCustomer() {
        return this.walletCustomer;
    }

    public List<CartItem> getListOfCartItem() {
        return this.listOfCartItem;
    }

    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }

    public String getAddressId() {
        return this.addressId;
    }
    // --- SETTERS FOR LINKS

    public void setAccount(Account account) {
        this.account = account;
    }

    // --- toString specific method
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(idCustomer);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(phoneNumber);
        sb.append("|");
        sb.append(gender);
        sb.append("|");
        sb.append(birthday);
        sb.append("|");
        sb.append(imgUrl);

        sb.append("|");
        sb.append(pubkey);
        return sb.toString();
    }

}
