/*
 * Created on 2022-05-06 ( 17:51:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package backend.backend.persitence.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "EvaluateReply"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Evaluate_Reply", schema="dbo", catalog="shop" )
public class EvaluateReply implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_evaluate_reply", nullable=false)
    private Integer    idEvaluateReply ;

    //--- ENTITY DATA FIELDS 
    @Column(name="id_evaluate")
    private Integer    idEvaluate ;

    @Column(name="id_shop")
    private Integer    idShop ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_create")
    private Date       dateCreate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_update")
    private Date       dateUpdate ;

    @Column(name="content", length=2147483647)
    private String     content ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="id_evaluate", referencedColumnName="id_evaluate", insertable=false, updatable=false)
    private Evaluate   evaluate ; 

    @ManyToOne
    @JoinColumn(name="id_shop", referencedColumnName="id_shop", insertable=false, updatable=false)
    private Shop       shop ; 


    /**
     * Constructor
     */
    public EvaluateReply() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdEvaluateReply( Integer idEvaluateReply ) {
        this.idEvaluateReply = idEvaluateReply ;
    }
    public Integer getIdEvaluateReply() {
        return this.idEvaluateReply;
    }

    public void setIdEvaluate( Integer idEvaluate ) {
        this.idEvaluate = idEvaluate ;
    }
    public Integer getIdEvaluate() {
        return this.idEvaluate;
    }

    public void setIdShop( Integer idShop ) {
        this.idShop = idShop ;
    }
    public Integer getIdShop() {
        return this.idShop;
    }

    public void setDateCreate( Date dateCreate ) {
        this.dateCreate = dateCreate ;
    }
    public Date getDateCreate() {
        return this.dateCreate;
    }

    public void setDateUpdate( Date dateUpdate ) {
        this.dateUpdate = dateUpdate ;
    }
    public Date getDateUpdate() {
        return this.dateUpdate;
    }

    public void setContent( String content ) {
        this.content = content ;
    }
    public String getContent() {
        return this.content;
    }

    //--- GETTERS FOR LINKS
    public Evaluate getEvaluate() {
        return this.evaluate;
    } 

    public Shop getShop() {
        return this.shop;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idEvaluateReply);
        sb.append("|");
        sb.append(idEvaluate);
        sb.append("|");
        sb.append(idShop);
        sb.append("|");
        sb.append(dateCreate);
        sb.append("|");
        sb.append(dateUpdate);
        sb.append("|");
        sb.append(content);
        return sb.toString(); 
    } 

}
