/*
 * Created on 2022-03-29 ( 21:59:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package backend.backend.persitence.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * JPA entity class for "ResetToken"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "reset_token", schema = "dbo", catalog = "shop")
public class ResetToken implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @JoinColumn(name = "ID_ACCOUNT", referencedColumnName = "ID_ACCOUNT")
    private int idAccount;

    // --- ENTITY DATA FIELDS
    @Column(name = "reset_token_content", length = 2147483647)
    private String resetTokenContent;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "reset_token_expires")
    private Date resetTokenExpires;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "password_reset")
    private Date passwordReset;

    // --- ENTITY LINKS ( RELATIONSHIP )
    @OneToOne
    @JoinColumn(name = "ID_ACCOUNT", referencedColumnName = "ID_ACCOUNT", insertable = false, updatable = false)
    private Account account;

    /**
     * Constructor
     */
    public ResetToken() {
        super();
    }

    public ResetToken(int idAccount) {
        this.idAccount = idAccount;
    }

    public ResetToken(int idAccount, Date passwordReset, String resetTokenContent, Date resetTokenExpires) {
        this.idAccount = idAccount;
        this.passwordReset = passwordReset;
        this.resetTokenContent = resetTokenContent;
        this.resetTokenExpires = resetTokenExpires;
    }

    // --- GETTERS & SETTERS FOR FIELDS
    public void setIdAccount(int idAccount) {
        this.idAccount = idAccount;
    }

    public int getIdAccount() {
        return this.idAccount;
    }

    public void setResetTokenContent(String resetTokenContent) {
        this.resetTokenContent = resetTokenContent;
    }

    public String getResetTokenContent() {
        return this.resetTokenContent;
    }

    public void setResetTokenExpires(Date resetTokenExpires) {
        this.resetTokenExpires = resetTokenExpires;
    }

    public Date getResetTokenExpires() {
        return this.resetTokenExpires;
    }

    public void setPasswordReset(Date passwordReset) {
        this.passwordReset = passwordReset;
    }

    public Date getPasswordReset() {
        return this.passwordReset;
    }

    // --- GETTERS FOR LINKS
    public Account getAccount() {
        return this.account;
    }
    public void setAccount(Account account) {
         this.account = account;
         
    }

    // --- toString specific method
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(idAccount);
        sb.append("|");
        sb.append(resetTokenContent);
        sb.append("|");
        sb.append(resetTokenExpires);
        sb.append("|");
        sb.append(passwordReset);
        return sb.toString();
    }

}
