/*
 * Created on 2022-05-06 ( 17:51:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package backend.backend.persitence.entities;

import java.io.Serializable;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.MapsId;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import backend.backend.helpers.payload.dto.AddressDTO;
import backend.backend.helpers.payload.dto.AddrressCellDTO;
import backend.backend.helpers.utils.SubUtils;

/**
 * JPA entity class for "Shop"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "Shop", schema = "dbo", catalog = "shop")
public class Shop implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @Column(name = "id_shop", nullable = false)
    private Integer idShop;

    // --- ENTITY DATA FIELDS
    @Column(name = "name", length = 2147483647)
    private String name;

    @Column(name = "phone_number", length = 15)
    private String phoneNumber;

    @Column(name = "img_url", length = 2147483647)
    private String imgUrl;

    @Column(name = "description", length = 2147483647)
    private String description;
    @Column(name = "address_id", nullable = false)
    private String addressId;

    // --- ENTITY LINKS ( RELATIONSHIP )

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "id_shop", referencedColumnName = "ID_ACCOUNT", insertable = false, updatable = false)
    @MapsId
    private Account account;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "address_id", referencedColumnName = "id", insertable = false, updatable = false)
    private Addrress addrress;

    /**
     * Constructor
     */
    public Shop() {
        super();
    }

    public Shop(Integer idShop, String name, String phoneNumber, String imgUrl, String description, String addressId) {
        this.idShop = idShop;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.imgUrl = imgUrl;
        this.description = description;
        this.addressId = addressId;

    }

    // --- GETTERS & SETTERS FOR FIELDS
    public void setIdShop(Integer idShop) {
        this.idShop = idShop;
    }

    public Integer getIdShop() {
        return this.idShop;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getImgUrl() {
        return this.imgUrl;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDescription() {
        return this.description;
    }

    // --- GETTERS FOR LINKS


    public void setAddressId(String addressId) {
        this.addressId = addressId;
    }

    public String getAddressId() {
        return this.addressId;
    }

    public void setAddrress(Addrress addrress) {
        this.addrress = addrress;
    }

    public Addrress getAddress() {
        return this.addrress;
    }

    public void setAddressDTO(AddressDTO addressDTO) {
        this.addrress = (Addrress) SubUtils.mapperObject(addressDTO, new Addrress());
    }

    public AddressDTO getAddressDTO() {
        return new AddressDTO(
                (AddrressCellDTO) SubUtils.mapperObject(this.addrress.getAddrressCell3(), new AddrressCellDTO()),
                (AddrressCellDTO) SubUtils.mapperObject(this.addrress.getAddrressCell2(), new AddrressCellDTO()),
                (AddrressCellDTO) SubUtils.mapperObject(this.addrress.getAddrressCell(), new AddrressCellDTO()),
                this.addrress.getSubLocate());
    }

    public void setAccount(Account account) {
        this.account = account;
    }

    // --- toString specific method
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(idShop);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(phoneNumber);
        sb.append("|");
        sb.append(imgUrl);
        sb.append("|");

        sb.append(description);
        return sb.toString();
    }

}
