/*
 * Created on 2022-05-06 ( 17:51:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package backend.backend.persitence.entities;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

/**
 * JPA entity class for "ShopCategory"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name = "Shop_Category", schema = "dbo", catalog = "shop")
public class ShopCategory implements Serializable {

    private static final long serialVersionUID = 1L;

    // --- ENTITY PRIMARY KEY
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id_shop_category", nullable = false)
    private Integer idShopCategory;

    // --- ENTITY DATA FIELDS
    @Column(name = "id_shop")
    private Integer idShop;

    @Column(name = "name", length = 2147483647)
    private String name;

    // --- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name = "id_shop", referencedColumnName = "id_shop", insertable = false, updatable = false)
    private Shop shop;

    @OneToMany(mappedBy = "shopCategory")
    private List<SingleProductPage> listOfSingleProductPage;

    /**
     * Constructor
     */
    public ShopCategory() {
        super();
    }

    // --- GETTERS & SETTERS FOR FIELDS
    public void setIdShopCategory(Integer idShopCategory) {
        this.idShopCategory = idShopCategory;
    }

    public Integer getIdShopCategory() {
        return this.idShopCategory;
    }

    public void setIdShop(Integer idShop) {
        this.idShop = idShop;
    }

    public Integer getIdShop() {
        return this.idShop;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getName() {
        return this.name;
    }

    // --- GETTERS FOR LINKS
    public Shop getShop() {
        return this.shop;
    }

    public List<SingleProductPage> getListOfSingleProductPage() {
        return this.listOfSingleProductPage;
    }

    // --- toString specific method
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(idShopCategory);
        sb.append("|");
        sb.append(idShop);
        sb.append("|");
        sb.append(name);
        return sb.toString();
    }

}
