/*
 * Created on 2022-05-06 ( 17:51:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package backend.backend.persitence.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "Voucher"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Voucher", schema="dbo", catalog="shop" )
public class Voucher implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id_voucher", nullable=false)
    private Integer    idVoucher ;

    //--- ENTITY DATA FIELDS 
    @Column(name="id_sale")
    private Integer    idSale ;

    @Column(name="name", length=2147483647)
    private String     name ;

    @Column(name="code", length=2147483647)
    private String     code ;

    @Column(name="quantity_left")
    private Integer    quantityLeft ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_start")
    private Date       dateStart ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_end")
    private Date       dateEnd ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="id_sale", referencedColumnName="id_sale", insertable=false, updatable=false)
    private Sale       sale ; 


    /**
     * Constructor
     */
    public Voucher() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdVoucher( Integer idVoucher ) {
        this.idVoucher = idVoucher ;
    }
    public Integer getIdVoucher() {
        return this.idVoucher;
    }

    public void setIdSale( Integer idSale ) {
        this.idSale = idSale ;
    }
    public Integer getIdSale() {
        return this.idSale;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setCode( String code ) {
        this.code = code ;
    }
    public String getCode() {
        return this.code;
    }

    public void setQuantityLeft( Integer quantityLeft ) {
        this.quantityLeft = quantityLeft ;
    }
    public Integer getQuantityLeft() {
        return this.quantityLeft;
    }

    public void setDateStart( Date dateStart ) {
        this.dateStart = dateStart ;
    }
    public Date getDateStart() {
        return this.dateStart;
    }

    public void setDateEnd( Date dateEnd ) {
        this.dateEnd = dateEnd ;
    }
    public Date getDateEnd() {
        return this.dateEnd;
    }

    //--- GETTERS FOR LINKS
    public Sale getSale() {
        return this.sale;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idVoucher);
        sb.append("|");
        sb.append(idSale);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(code);
        sb.append("|");
        sb.append(quantityLeft);
        sb.append("|");
        sb.append(dateStart);
        sb.append("|");
        sb.append(dateEnd);
        return sb.toString(); 
    } 

}
