/*
 * Created on 2022-05-06 ( 17:51:48 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package backend.backend.persitence.entities;

import java.io.Serializable;

import javax.persistence.*;

/**
 * JPA entity class for "WalletShop"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="Wallet_Shop", schema="dbo", catalog="shop" )
public class WalletShop implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="id_shop", nullable=false)
    private Integer    idShop ;

    //--- ENTITY DATA FIELDS 
    @Column(name="total")
    private Double total ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @OneToOne
    @JoinColumn(name="id_shop", referencedColumnName="id_shop", insertable=false, updatable=false)
    private Shop       shop ; 


    /**
     * Constructor
     */
    public WalletShop() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setIdShop( Integer idShop ) {
        this.idShop = idShop ;
    }
    public Integer getIdShop() {
        return this.idShop;
    }

    public void setTotal( Double total ) {
        this.total = total ;
    }
    public Double getTotal() {
        return this.total;
    }

    //--- GETTERS FOR LINKS
    public Shop getShop() {
        return this.shop;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(idShop);
        sb.append("|");
        sb.append(total);
        return sb.toString(); 
    } 

}
